# Generated by Django 2.2.2 on 2020-01-09 18:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Администратор'), ('M', 'Менеджер'), ('C', 'Клиент')], default='C', max_length=2, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Profile')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата рождения')),
                ('passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия и номер паспорта')),
                ('starts_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('expires_date', models.DateField(blank=True, null=True, verbose_name='Действителен до')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Телефон введён в неверном формате.', regex='^\\+7\\s\\(\\d{3}\\)\\s\\d{3}-\\d{2}-\\d{2}')], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
                'db_table': 'ClientProfile',
            },
            bases=('users.profile',),
        ),
    ]
