# Generated by Django 2.2.2 on 2020-01-02 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0013_auto_20200102_1947'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(verbose_name='Итоговая сумма')),
                ('date_started', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='CruiseCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Сумма')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart', verbose_name='Корзина')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Cruise')),
                ('date_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TourDate', verbose_name='Дата бронирования')),
                ('services', models.ManyToManyField(blank=True, null=True, to='catalog.Service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Элемент корзины - круиз',
                'verbose_name_plural': 'Элементы корзины - круизы',
                'db_table': 'Cruise_cart_item',
            },
        ),
        migrations.CreateModel(
            name='BusTourCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Сумма')),
                ('bustour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.BusTour')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart', verbose_name='Корзина')),
                ('date_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.TourDate', verbose_name='Дата бронирования')),
                ('services', models.ManyToManyField(blank=True, null=True, to='catalog.Service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Элемент корзины - автобусный тур',
                'verbose_name_plural': 'Элементы корзины - автобусные туры',
                'db_table': 'Bus_tour_cart_item',
            },
        ),
    ]
