# Generated by Django 2.2.2 on 2020-01-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustourcartitem',
            name='bustour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.BusTour', verbose_name='Автобусный тур'),
        ),
        migrations.AlterField(
            model_name='bustourcartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='bustourcartitem',
            name='services',
            field=models.ManyToManyField(blank=True, to='catalog.Service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='cruisecartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cruisecartitem',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Cruise', verbose_name='Криуз'),
        ),
        migrations.AlterField(
            model_name='cruisecartitem',
            name='services',
            field=models.ManyToManyField(blank=True, to='catalog.Service', verbose_name='Услуги'),
        ),
    ]
