# Generated by Django 2.2.2 on 2020-01-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200107_1411'),
        ('carts', '0002_auto_20200102_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruisecartitem',
            name='cabin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Cabin', verbose_name='Каюта'),
        ),
        migrations.AlterField(
            model_name='bustourcartitem',
            name='bustour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bustours', to='catalog.BusTour', verbose_name='Автобусный тур'),
        ),
        migrations.AlterField(
            model_name='cruisecartitem',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruises', to='catalog.Cruise', verbose_name='Криуз'),
        ),
    ]
