# Generated by Django 2.2.2 on 2020-01-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20200107_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustourcartitem',
            name='category',
            field=models.CharField(choices=[('BUS TOUR', 'Автобусный тур'), ('CRUISE', 'Круиз')], default='BUS TOUR', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='cruisecartitem',
            name='category',
            field=models.CharField(choices=[('BUS TOUR', 'Автобусный тур'), ('CRUISE', 'Круиз')], default='CRUISE', max_length=20, verbose_name='Категория'),
        ),
    ]
