# Generated by Django 2.2.2 on 2020-01-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200107_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustourcartitem',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Заказан'),
        ),
        migrations.AddField(
            model_name='cruisecartitem',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Заказан'),
        ),
    ]
