# Generated by Django 2.2.2 on 2019-10-11 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique_for_date='posted', verbose_name='Заголовок')),
                ('image', models.ImageField(default='default-news-image.jpg', upload_to='news_pics', verbose_name='Новостная обложка')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('date_posted', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'News',
                'ordering': ['-date_posted'],
            },
        ),
    ]
