# Generated by Django 2.2.2 on 2019-12-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news_pics/news-default-image.jpg', upload_to='news_pics', verbose_name='Новостная обложка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, unique_for_date='date_posted', verbose_name='Заголовок'),
        ),
    ]
