# Generated by Django 2.2.2 on 2019-10-09 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique_for_date='posted', verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое содержание')),
                ('image', models.ImageField(default='default.jpg', upload_to='blog_pics', verbose_name='Путь к картинке')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'статья блога',
                'verbose_name_plural': 'статьи блога',
                'db_table': 'Post',
                'ordering': ['-date_posted'],
            },
        ),
    ]
