# Generated by Django 2.2.2 on 2019-12-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191226_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_pics/blog-default-image.png', upload_to='blog_pics', verbose_name='Путь к картинке'),
        ),
    ]
