# Generated by Django 2.2.2 on 2019-12-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191219_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='content',
        ),
        migrations.AddField(
            model_name='tour',
            name='charges',
            field=models.TextField(default='nothing', verbose_name='Стоимость тура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='timeline',
            field=models.TextField(default='nothing', verbose_name='Программа тура'),
            preserve_default=False,
        ),
    ]
