# Generated by Django 2.2.2 on 2019-12-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191220_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(default='default_tour.jpg', upload_to='blog_pics', verbose_name='Путь к картинке')),
                ('timeline', models.TextField(verbose_name='Программа тура')),
                ('charges', models.TextField(verbose_name='Стоимость тура')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('group_size', models.PositiveSmallIntegerField(default=25, verbose_name='Количество мест')),
                ('category', models.CharField(choices=[('BUS TOUR', 'Автобусный тур'), ('CRUISE', 'Круиз')], default='BUS TOUR', max_length=20, verbose_name='Категория')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Автобусный тур',
                'verbose_name_plural': 'Автобусные туры',
                'db_table': 'Bus_tour',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(default='default_tour.jpg', upload_to='blog_pics', verbose_name='Путь к картинке')),
                ('timeline', models.TextField(verbose_name='Программа тура')),
                ('charges', models.TextField(verbose_name='Стоимость тура')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('group_size', models.PositiveSmallIntegerField(default=25, verbose_name='Количество мест')),
                ('category', models.CharField(choices=[('BUS TOUR', 'Автобусный тур'), ('CRUISE', 'Круиз')], default='BUS TOUR', max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Круиз',
                'verbose_name_plural': 'Круизы',
                'db_table': 'Cruise',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
