# Generated by Django 2.2.2 on 2019-12-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191221_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustour',
            name='category',
            field=models.CharField(choices=[('Автобусный тур', 'Автобусный тур'), ('Круиз', 'Круиз')], default='Автобусный тур', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='category',
            field=models.CharField(choices=[('Автобусный тур', 'Автобусный тур'), ('Круиз', 'Круиз')], default='Автобусный тур', max_length=20, verbose_name='Категория'),
        ),
    ]
