# Generated by Django 2.2.2 on 2019-12-23 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191221_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateField(default=datetime.date.today, verbose_name='Дата тура')),
            ],
            options={
                'verbose_name': 'Расписание тура',
                'verbose_name_plural': 'Расписание туров',
                'db_table': 'Tour_date',
                'ordering': ['tour_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='bustour',
            options={'ordering': ['title'], 'verbose_name': 'Автобусный тур', 'verbose_name_plural': 'Автобусные туры'},
        ),
        migrations.AlterModelOptions(
            name='cruise',
            options={'ordering': ['title'], 'verbose_name': 'Круиз', 'verbose_name_plural': 'Круизы'},
        ),
        migrations.AlterField(
            model_name='bustour',
            name='category',
            field=models.CharField(choices=[('BUS TOUR', 'Автобусный тур'), ('CRUISE', 'Круиз')], default='BUS TOUR', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='bustour',
            name='country',
            field=models.CharField(blank=True, choices=[('EST', 'Эстония'), ('LV', 'Латвия'), ('LT', 'Литва'), ('RU', 'Россия')], max_length=5, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='category',
            field=models.CharField(choices=[('BUS TOUR', 'Автобусный тур'), ('CRUISE', 'Круиз')], default='BUS TOUR', max_length=20, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='bustour',
            name='tourdates',
            field=models.ManyToManyField(to='catalog.TourDate', verbose_name='Даты тура'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='tourdates',
            field=models.ManyToManyField(to='catalog.TourDate', verbose_name='Даты тура'),
        ),
    ]
