# Generated by Django 2.2.2 on 2019-12-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191223_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='category',
            field=models.CharField(choices=[('BUS TOUR', 'Автобусный тур'), ('CRUISE', 'Круиз')], default='CRUISE', max_length=20, verbose_name='Категория'),
        ),
    ]
