# Generated by Django 2.2.2 on 2019-12-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191226_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustour',
            name='image',
            field=models.ImageField(default='catalog_pics/tour-default-image.png', upload_to='catalog_pics', verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='image',
            field=models.ImageField(default='catalog_pics/tour-default-image.png', upload_to='catalog_pics', verbose_name='Путь к картинке'),
        ),
    ]
