# Generated by Django 2.2.2 on 2020-01-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191230_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'Services',
            },
        ),
        migrations.AlterField(
            model_name='bustour',
            name='country',
            field=models.CharField(choices=[('EST', 'Эстония'), ('LV', 'Латвия'), ('LT', 'Литва'), ('RU', 'Россия')], max_length=5, verbose_name='Страна'),
        ),
    ]
