# Generated by Django 2.2.2 on 2020-01-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200101_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustour',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Service', verbose_name='Услуги'),
        ),
    ]
