# Generated by Django 2.2.2 on 2020-01-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200102_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на офиц. страницу')),
            ],
            options={
                'verbose_name': 'Паром',
                'verbose_name_plural': 'Паромы',
                'db_table': 'Ferry',
            },
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Класс каюты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(default='catalog_pics/cabin-default-image.png', upload_to='catalog_pics', verbose_name='Путь к картинке')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('n_passengers', models.SmallIntegerField(verbose_name='Число пассажиров')),
                ('ferry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Ferry', verbose_name='Паром')),
            ],
            options={
                'verbose_name': 'Каюта',
                'verbose_name_plural': 'Каюты',
                'db_table': 'Cabin',
            },
        ),
        migrations.AddField(
            model_name='cruise',
            name='ferry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Ferry', verbose_name='Паром'),
        ),
    ]
