# Generated by Django 2.2.2 on 2020-01-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200106_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='ferry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabins', to='catalog.Ferry', verbose_name='Паром'),
        ),
    ]
