# Generated by Django 2.2.2 on 2020-01-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200107_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='ferry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Ferry', verbose_name='Паром'),
        ),
    ]
