# Generated by Django 2.2.2 on 2020-06-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200107_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustour',
            name='n_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество дней'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='n_days',
            field=models.PositiveIntegerField(default=2, verbose_name='Количество дней'),
        ),
    ]
